apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: flask-app
  ports:
  - protocol: TCP
    port: 80           # External port
    targetPort: 5000    # Flask app's internal port
    nodePort: 31158     # NodePort (can be chosen manually)
  type: NodePort        # Change type to NodePort

